name: SimpleMythicChest
version: '${project.version}'
main: com.venned.simplemythicchest.Main
api-version: '1.20'
depend:
  - PlaceholderAPI
  - SuperiorSkyblock2
commands:
  mythicalchest:
    description: Cofres Miticos para poder almacenar
