title-sub-chest-available: "&cSub Chest %number_submenu%"
lore-sub-chest-available:
  - "&7Sub Menu %number_submenu%"

title-sub-chest-locked: "&c&l LOCKED"
lore-sub-chest-locked:
  - "&7Sub Menu %number_submenu%"
  - "&6Price %coins%"
  - "&cLocked"

# ITEM META CHEST

display-name-mythic: "&dMythical Chest &7[%level%]"
lore-mythic:
  - ""
  - "&7This Chest Mythic"

prices:
  1:
    coins: 4000
  2:
    coins: 9000
  3:
    coins: 13000
  4:
    coins: 19000
  5:
    coins: 20000
  6:
    coins: 24000

blocks-value:
  IRON_BLOCK: 50
  DIAMOND_BLOCK: 10
